### ISSUE TITLE
UHD750, does it work?

### ISSUE THREAD

**Issue by cuihairu** [zmlu/Hackintosh-OC-Asus-B560MN-i7-11700K-Rocketlake-UHD750#1]
Searched the web and found no examples of the UHD750 working properly, and looking at your screenshot, the UHD is the working mode.

**Comment by zmlu** [comment]
Actually, it doesn't work very well, which means it can only display basic graphics.

As you can see in my screenshot, the "Graphics" section, the VRAM is only 7mb.
